NODE_ENV = development

PORT = 5001

MONGO_URI = <MONGO_URI>

JWT_SECRET = jwt_secret
JWT_EXPIRY = number_of_days

CLOUDINARY_CLOUD_NAME = <CLOUDINARY_CLOUD_NAME>
CLOUDINARY_API_KEY = <CLOUDINARY_API_KEY>
CLOUDINARY_API_SECRET = <CLOUDINARY_API_SECRET>

SMTP_HOST = <SMTP_HOST>
SMTP_PORT = <SMTP_PORT>
SMTP_USERNAME = <SMTP_USERNAME>
SMTP_PASSWORD = <SMTP_PASSWORD>
SMTP_FROM_EMAIL = <SMTP_FROM_EMAIL>

RAZORPAY_KEY_ID = <RAZORPAY_KEY_ID>
RAZORPAY_SECRET = <RAZORPAY_SECRET>
RAZORPAY_PLAN_ID = <RAZORPAY_PLAN_ID>

# FRONTEND_URL =  http://localhost:5173
FRONTEND_URL = <FRONTEND_URL>

CONTACT_US_EMAIL = <YOUR_CONTACT_USE_EMAIL>